# Generated by Django 5.0.6 on 2024-05-30 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('stock', models.PositiveIntegerField(verbose_name='موجودی')),
                ('available', models.BooleanField(default=True, verbose_name='موجود است/نیست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='وزن بر اساس کیلوگرم')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='ابعاد به صورت متنی')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='اسم سازنده (برند)')),
                ('warranty', models.CharField(blank=True, max_length=255, verbose_name='اطلاعات گارانتی')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='رنگ محصول')),
                ('breed', models.CharField(blank=True, max_length=50, verbose_name='نژاد')),
                ('life_stage', models.CharField(blank=True, max_length=50, verbose_name='مرحله زندگی مناسب (سن)')),
                ('flavor', models.CharField(blank=True, max_length=50, verbose_name='طعم دهنده ')),
                ('nutritional_info', models.TextField(blank=True, verbose_name='اطلاعات تغذیه ای')),
                ('recommended_usage', models.TextField(blank=True, verbose_name='دستورالعمل استفاده توصیه شده')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('origin_country', models.CharField(blank=True, max_length=100, verbose_name='کشور سازنده')),
                ('is_featured', models.BooleanField(default=False, verbose_name='تخفیف')),
                ('featured_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت تخفیف خورده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='دسته\u200cبندی')),
                ('tags', models.ManyToManyField(blank=True, to='products.tag', verbose_name='برچسب ها برای جستجو و فیلتر')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول')),
            ],
        ),
    ]
